//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by zdoom.rc
//
#define IDC_SAVEREPORT                  8
#define IDNO2                           9
#define IDD_MIDASINITERROR              108
#define IDD_IWADDIALOG                  112
#define IDC_INVISIBLECURSOR             114
#define IDD_CRASHDIALOG                 122
#define IDD_EAXPROPERTYLIST             123
#define IDD_DIALOG1                     124
#define IDD_EAXEDIT                     124
#define IDD_DIALOG2                     125
#define IDD_NEWEAX                      125
#define IDD_DIALOG3                     127
#define IDD_DIALOG4                     128
#define IDD_SAVEEAX                     128
#define IDB_BITMAP1                     131
#define IDB_DEADGUY                     131
#define IDD_CRASHDETAILS                133
#define IDI_BOING1                      137
#define IDI_BOING2                      138
#define IDI_BOING3                      139
#define IDI_BOING4                      140
#define IDI_BOING5                      141
#define IDI_BOING6                      142
#define IDI_BOING7                      143
#define IDI_BOING8                      144
#define IDD_BOING                       145
#define IDD_CRASHOVERVIEW               147
#define IDB_DMFLAGS                     149
#define IDB_GENERALSETTINGS             150
#define IDI_ICONST                      151
#define IDR_MAINMENU                    152
#define IDD_ADDBOT                      153
#define IDD_BANIP                       154
#define IDD_BANLIST                     155
#define IDD_KICKBAN		                156
#define IDD_CHANGEMAP                   157
#define IDD_EDITBAN                     159
#define IDD_GENERALSETTINGS             160

// 161 was the old kick dialog, which
// was merged with the ban dialog. [RC]

#define IDD_LMSSETTINGS                 162
#define IDD_MAPROTATION                 163
#define IDD_MESSAGES                    164
#define IDD_REMOVEBOT                   165
#define IDD_SERVERDIALOG                166
#define IDD_SERVERINFO                  167
#define IDD_SERVERSTATISTICS            168
#define IDD_ERRORPANE                   148
#define IDD_NETSTARTPANE                149
#define IDC_ERRORMESSAGE                1004
#define IDQUIT                          1005
#define IDC_IWADLIST                    1006
#define IDC_DONTASKIWAD                 1007
#define IDC_SPIN1                       1010
#define IDC_SPINID1                     1010
#define IDC_CRASHINFO                   1011
#define IDC_SPINID2                     1011
#define IDC_TOOLTIP1                    1012
#define IDCE_ENVIRONMENTSIZE            1025
#define IDCS_ENVIRONMENTSIZE            1026
#define IDC_DECAYTIMESCALE              1027
#define IDC_REFLECTIONSSCALE            1028
#define IDC_REFLECTIONSDELAYSCALE       1029
#define IDC_REVERBSCALE                 1030
#define IDC_REVERBDELAYSCALE            1031
#define IDC_DECAYHFLIMIT                1032
#define IDC_ECHOTIMESCALE               1033
#define IDC_MODULATIONTIMESCALE         1034
#define IDC_DUMMY                       1035
#define IDC_NEW                         1036
#define IDC_SAVE                        1037
#define IDC_REVERT                      1038
#define IDC_CURRENTENVIRONMENT          1039
#define IDC_ID2                         1040
#define IDC_ID1                         1041
#define IDC_SHOWIDS                     1043
#define IDC_LIST3                       1047
#define IDC_ENVIRONMENTLIST             1047
#define IDC_SIZEBOX                     1048
#define IDC_EDIT1                       1049
#define IDC_NEWENVNAME                  1049
#define IDC_CRASHFILECONTENTS           1049
#define IDC_BOINGEDIT                   1049
#define IDC_IPADDRESS                   1049
#define IDC_BANFILE                     1049
#define IDC_REASON                      1049
#define IDC_MAPNAME                     1049
#define IDC_BANBOX                      1049
#define IDC_INPUTBOX                    1049
#define IDC_LOGFILE                     1049
#define IDC_PASSWORD                    1049
#define IDC_EDITID1                     1050
#define IDC_EDITID2                     1051
#define IDC_HOTKEY1                     1053
#define IDC_LIST1                       1054
#define IDC_ENVLIST                     1054
#define IDC_CRASHFILES                  1054
#define IDC_BOTLIST                     1054
#define IDC_BANLIST                     1054
#define IDC_PLAYERNAMES                 1054
#define IDC_PLAYERLIST                  1054
#define IDC_MAPLISTBOX                  1054
#define IDC_SELECTALL                   1055
#define IDC_SELECTNONE                  1056
#define IDC_SAVEGROUP                   1057
#define IDC_TESTEAX                     1058
#define IDC_RICHEDIT21                  1059
#define IDC_CRASHHEADER                 1059
#define IDC_RICHEDIT22                  1061
#define IDC_PLEASETELLUS                1061
#define IDC_BUTTON2                     1062
#define IDC_CRASHDETAILS                1062
#define IDC_REMOVE                      1062
#define IDC_DEADGUYVIEWER               1063
#define IDC_BOING                       1065
#define IDC_CRASHFILESIZE               1066
#define IDC_BUTTON1                     1071
#define IDC_EDIT                        1071
#define IDC_SEND                        1071
#define IDC_BOINGSTATUS                 1072
#define IDC_BOINGPROGRESS               1073
#define IDC_TAB1                        1074
#define IDC_CRASHTAB                    1074
#define IDC_RICHEDIT23                  1075
#define IDC_CRASHSUMMARY                1075
#define IDC_ERRORTEXT                   1076
#define IDC_ICONPIC                     1077
#define IDC_DIVIDERBAR                  1078
#define IDC_PROGRESS1                   1079
#define IDC_NETSTARTPROGRESS            1079
#define IDC_NETSTARTMESSAGE             1080
#define IDC_NETSTARTCOUNT               1081
#define IDC_STATIC_TITLE				1082
#define IDC_STATIC_STARTUP				1083
#define IDC_ADD                         1076
#define IDC_BANCOMMENT                  1077
#define IDC_CLEAR                       1078
#define IDC_ENFORCEBANS                 1079
#define IDC_BAN                         1080
#define IDC_INTERMISSION                1081
#define IDCE_ENVIRONMENTDIFFUSION       1085
#define IDCS_ENVIRONMENTDIFFUSION       1086
#define IDCE_ROOM                       1087
#define IDCS_ROOM                       1088
#define IDCE_ROOMHF                     1089
#define IDCS_ROOMHF                     1090
#define IDCE_ROOMLF                     1091
#define IDCS_ROOMLF                     1092
#define IDCE_DECAYTIME                  1093
#define IDCS_DECAYTIME                  1094
#define IDCE_DECAYHFRATIO               1095
#define IDCS_DECAYHFRATIO               1096
#define IDCE_DECAYLFRATIO               1097
#define IDCS_DECAYLFRATIO               1098
#define IDCE_REFLECTIONS                1099
#define IDCS_REFLECTIONS                1100
#define IDCE_REFLECTIONSDELAY           1101
#define IDCS_REFLECTIONSDELAY           1102
#define IDCE_REFLECTIONSPANX            1103
#define IDCS_REFLECTIONSPANX            1104
#define IDCE_REFLECTIONSPANY            1105
#define IDCS_REFLECTIONSPANY            1106
#define IDCE_REFLECTIONSPANZ            1107
#define IDCS_REFLECTIONSPANZ            1108
#define IDCE_REVERB                     1109
#define IDCS_REVERB                     1110
#define IDCE_REVERBDELAY                1111
#define IDCS_REVERBDELAY                1112
#define IDCE_REVERBPANX                 1113
#define IDCS_REVERBPANX                 1114
#define IDCE_REVERBPANY                 1115
#define IDCS_REVERBPANY                 1116
#define IDCE_REVERBPANZ                 1117
#define IDCS_REVERBPANZ                 1118
#define IDCE_ECHOTIME                   1119
#define IDCS_ECHOTIME                   1120
#define IDCE_ECHODEPTH                  1121
#define IDCS_ECHODEPTH                  1122
#define IDCE_MODULATIONTIME             1123
#define IDCS_MODULATIONTIME             1124
#define IDCE_MODULATIONDEPTH            1125
#define IDCS_MODULATIONDEPTH            1126
#define IDCE_AIRABSORPTIONHF            1127
#define IDCS_AIRABSORPTIONHF            1128
#define IDCE_HFREFERENCE                1129
#define IDCS_HFREFERENCE                1130
#define IDCE_LFREFERENCE                1131
#define IDCS_LFREFERENCE                1132
#define IDCE_ROOMROLLOFFFACTOR          1133
#define IDCS_ROOMROLLOFFFACTOR          1134
#define IDCS_REFLECTIONSDELAY2          1135
#define IDC_TITLEBOX                    1142
#define IDC_SCOREBOARD1                 1143
#define IDC_SCOREBOARD2                 1144
#define IDC_SCOREBOARD3                 1145
#define IDC_SCOREBOARD4                 1146
#define IDC_CONSOLEBOX                  1147
#define IDC_USEMAPROTATIONLIST          1149
#define IDC_USERANDOMMAP                1150
#define IDC_REMOVEALLBOTS               1151
#define IDC_ENABLELOGGING               1152
#define IDC_TIMESTAMPFORMAT             1153
#define IDC_TIMESTAMP                   1154
#define IDC_STRIPCODES                  1155
#define IDC_DONOTSTRIPCODES             1156
#define IDC_LEAVEINFORMAT               1157
#define IDC_LMS_ALLOWCHAINSAW           1158
#define IDC_LMS_ALLOWPISTOL             1159
#define IDC_LMS_ALLOWSHOTGUN            1160
#define IDC_LMS_ALLOWSSG                1161
#define IDC_LMS_ALLOWCHAINGUN           1162
#define IDC_LMS_ALLOWMINIGUN            1163
#define IDC_LMS_ALLOWROCKETLAUNCHER     1164
#define IDC_LMS_ALLOWGRENADELAUNCHER    1165
#define IDC_LMS_ALLOWPLASMA             1166
#define IDC_LMS_ALLOWRAILGUN            1167
#define IDC_LMS_SPECTATORVIEW           1168
#define IDC_LMS_SPECTATORTALK           1169
#define IDC_LMSALLOWEDWEAPONS           1170
#define IDC_LMSSPECTATORSETTINGS        1171
#define IDC_KICK                        1172
#define IDC_REQUIREPW                   1173
#define IDC_REQUIREJOINPW               1174
#define IDC_JOINPASSWORD                1175
#define IDC_RCONPASSWORD                1176
#define IDC_MAXCLIENTS                  1177
#define IDC_MAXPLAYERS                  1178
#define IDC_SPIN6                       1181
#define IDC_MOTD                        1182
#define IDC_MASTERIP                    1183
#define IDC_UPDATEMASTER                1184
#define IDC_BROADCAST                   1185
#define IDC_SHOWLAUNCHERQUERIES         1186
#define IDC_CONNECTIONTYPE              1187
#define IDC_SERVERNAME                  1188
#define IDC_WADURL                      1189
#define IDC_EMAIL                       1190
#define IDC_GAMEPLAYMODE                1191
#define IDC_SKILL                       1192
#define IDC_BOTSKILL                    1193
#define IDC_FRAGLIMIT                   1194
#define IDC_TIMELIMIT                   1195
#define IDC_POINTLIMIT                  1196
#define IDC_DUELLIMIT                   1197
#define IDC_WINLIMIT                    1198
#define IDC_MAXLIVES                    1199
#define IDC_SPIN4                       1200
#define IDC_SPIN5                       1201
#define IDC_SPIN7                       1202
#define IDC_SPIN8                       1203
#define IDC_CURRENTMAP                  1204
#define IDC_AVGNUMPLAYERS               1205
#define IDC_MAXPLAYERSATONETIME         1206
#define IDC_TOTALFRAGS                  1207
#define IDC_TOTALUPTIME                 1208
#define IDC_TOTALINBOUNDDATATRANSFER    1209
#define IDC_TOTALOUTBOUNDDATATRANSFER   1210
#define IDC_AVERAGEINBOUNDDATATRANSFER  1211
#define IDC_AVERAGEOUTBOUNDDATATRANSFER 1212
#define IDC_PEAKINBOUNDDATATRANSFER     1213
#define IDC_PEAKOUTBOUNDDATATRANSFER    1214
#define IDC_CURRENTINBOUNDDATATRANSFER  1215
#define IDC_CURRENTOUTBOUNDDATATRANSFER 1216
#define IDC_OPERATINGSYSTEM             1217
#define IDC_CPUSPEED                    1218
#define IDC_VENDOR                      1219
#define IDC_GAME                        1220
#define IDC_EMAILADDRESS                1221
#define IDC_PWADS                       1222
#define IDC_VERSION                     1223
#define IDC_SPIN9                       1232
#define UWM_TRAY_TRAYID                 32769
#define UWM_TRAY_NOP                    32770
#define ID_FILE_IMPORTCONFIGURATION     4001
#define ID_FILE_EXPORTCONFIGURATION     4002
#define ID_FILE_EXIT                    4003
#define ID_SETTINGS_GENERALSETTINGS     4004
#define ID_SETTINGS_CONFIGREDMFLAGS     4005
#define ID_SETTINGS_MAPROTATION         4006
#define ID_SETTINGS_LMSSETTINGS         4007
#define ID_SETTINGS_MESSAGES            4008
#define ID_SERVER_GENERALINFORMATION    4009
#define ID_SERVER_STATISTICS            4010
#define ID_ADMIN_ADDBOT                 4011
#define ID_ADMIN_REMOVEBOT              4012
//#define ID_ADMIN_KICKPLAYER           4013
#define ID_ADMIN_KICKBAN		        4014
#define ID_ADMIN_VIEWBANLIST            4015
#define ID_ADMIN_BANIP                  4016
#define ID_ADMIN_CHANGEMAP              4017
#define IDC_WELCOME_VERSION				4019
#define IDC_WELCOME_OPENGL				4020
#define IDC_WELCOME_SOFTWARE			4021
#define IDC_WELCOME_FULLSCREEN			4022
#define IDC_WELCOME_COMPAT				4023
#define IDC_WELCOME_SHIFTLABEL			4024
#define	IDR_PLAYER_KICK					4025
#define	IDR_PLAYER_KICK_WHY				4026
#define	IDR_PLAYER_BAN					4027
#define	IDR_PLAYER_BAN_WHY				4028
#define	IDR_BOT_REMOVE					4029
#define	IDR_BOT_REMOVEALL				4030
#define	IDR_BOT_CLONE					4031
#define	IDD_REASON						4032
#define	IDC_REASON_NAME					4033
#define IDC_REASON_DETAILS				4034
#define	IDC_REASON_BAN					4035
#define IDC_KICKBAN_KICK				4036
#define IDC_KICKBAN_KICKANDBAN			4037
#define IDC_SERVER_STATUSBAR			4039
#define	IDR_PLAYER_GETIP				4040
#define IDD_GOTIP						4041
#define IDC_GOTIP_IP					4042
#define IDC_SPIN2                       4043
#define IDC_SPIN3                       4044
#define G15_ICON_ORION					4045
#define G15_ICON_ARMOR					4046
#define G15_ICON_STIMPACK				4047
#define G15_ICON_SHELLS					4048
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         40025
#define _APS_NEXT_CONTROL_VALUE         1224
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
