#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DMFLAGS_COOP                        501
#define IDD_DMFLAGS_DM                          503
#define IDD_DMFLAGS                             504
#define IDD_DMFLAGS_GENERAL                     506
#define IDD_DMFLAGS_COMPAT                      508
#define IDD_DMFLAGS_PLAYERS                     511
#define IDC_TITLE                               1000
#define IDC_BARRELS_RESPAWN                     2027
#define IDC_COMPATF_BOOMSCROLL                  2036
#define IDC_COMPATF_DEHHEALTH                   2037
#define IDC_COMPATF_DROPOFF                     2038
#define IDC_COMPATF_INVISIBILITY                2039
#define IDC_COMPATF_RAVENSCROLL                 2040
#define IDC_COMPATF_SOUNDTARGET                 2041
#define IDC_COMPATF_TRACE                       2042
#define IDC_COOP_HALVE_AMMO                     2045
#define IDC_COOP_LOSE_AMMO                      2046
#define IDC_COOP_LOSE_ARMOR                     2047
#define IDC_COOP_LOSE_INVENTORY                 2048
#define IDC_COOP_LOSE_POWERUPS                  2049
#define IDC_DISABLESTEALTHMONSTERS              2064
#define IDC_FAST_MONSTERS                       2084
#define IDC_FORCE_RESPAWN                       2087
#define IDC_INFINITE_AMMO                       2095
#define IDC_INSTANTRESPAWN                      2099
#define IDC_ITEMS_RESPAWN                       2103
#define IDC_LIMITED_AIRMOVEMENT                 2107
#define IDC_LIMITPAIN                           2108
#define IDC_LOSE_KEYS                           2125
#define IDC_LOSE_WEAPONS                        2126
#define IDC_MONSTERS_RESPAWN                    2137
#define IDC_NO_COOP_MP_WEAPON_SPAWN             2142
#define IDC_NO_FOV                              2144
#define IDC_NO_FREELOOK                         2145
#define IDC_NO_PASSMOBJ                         2150
#define IDC_NO_RESPAWN_INVUL                    2151
#define IDC_NODOORLIGHT                         2155
#define IDC_NOTOSSDROPS                         2156
#define IDC_OLDINTERMISSION                     2157
#define IDC_ORIGINALSOUNDCURVE                  2158
#define IDC_PLASMA_BUMP_BUG                     2162
#define IDC_RESPAWN_SUPER                       2178
#define IDC_SAME_SPAWN_SPOT                     2183
#define IDC_SHORTTEX                            2195
#define IDC_SHOTGUN_START                       2196
#define IDC_DF2_YES_KEEP_FRAGS                  2233
#define IDC_DF2_NO_RESPAWN                      2251
#define IDC_DF2_YES_LOSEFRAG                    2252
#define IDC_DF2_INFINITE_INVENTORY              2253
#define IDC_DF2_KILL_MONSTERS                   2254
#define IDC_DF2_NO_AUTOMAP                      2255
#define IDC_DF2_NO_AUTOMAP_ALLIES               2256
#define IDC_DF2_DISALLOW_SPYING                 2257
#define IDC_DF2_CHASECAM                        2258
#define IDC_DF2_NOSUICIDE                       2259
#define IDC_DF2_NOAUTOAIM                       2260
#define IDC_DF2_FORCE_GL_DEFAULTS               2261
#define IDC_DF2_NO_ROCKET_JUMPING               2262
#define IDC_DF2_FORCE_ALPHA                     2264
#define IDC_COMPATF_SILENT_INSTANT_FLOORS       2275
#define IDC_COMPATF_SECTORSOUNDS                2276
#define IDC_COMPATF_MISSILECLIP                 2277
#define IDC_COMPATF_CROSSDROPOFF                2278
#define IDC_COMPATF_OLDRADIUSDMG                2279
#define IDC_COMPATF_NO_CROSSHAIR                2280
#define IDC_COMPATF_OLD_WEAPON_SWITCH           2281
#define IDC_COMPATF2_NETSCRIPTS_ARE_CLIENTSIDE  2284
#define IDC_DMF_JUMPING                         2286
#define IDC_DMF_CROUCHING                       2288
#define IDC_FALLINGDAMAGE                       2289
#define IDC_DF2_AWARD_DAMAGE_INSTEAD_KILLS      2290
#define IDC_SPAWN_FARTHEST                      2300
#define IDC_STAIRINDEX                          2305
#define IDC_USEBLOCKING                         2318
#define IDC_WALLRUN                             2323
#define IDC_YES_DEGENERATION                    2334
#define IDC_YES_DOUBLEAMMO                      2335
#define IDC_YES_FREEAIMBFG                      2336
#define IDC_YES_WEAPONDROP                      2337
#define IDC_FLAGSTABCONTROL                     2421
#define IDC_NO_TEAM_SWITCH                      2423
#define IDC_NO_TEAM_SELECT                      2424
#define IDC_INSTANT_RETURN                      2425
#define IDC_DF2_YES_KEEP_TEAMS                  2426
#define IDC_DISABLETAUNTS                       2429
#define IDC_WEAPONS_STAY                        2432
#define IDC_NO_RUNES                            2433
#define IDC_NO_MONSTERS                         2434
#define IDC_NO_ARMOR                            2435
#define IDC_MAGICSILENCE                        2436
#define IDC_SILENTPICKUP                        2437
#define IDC_DMF_EXIT1                           2438
#define IDC_NO_HEALTH1                          2440
#define IDC_COMPATFLAGS_VALUE                   2445
#define IDC_COMPATFLAGS2_VALUE                  2446
#define IDC_DMFLAGS_VALUE                       2447
#define IDC_DMFLAGS2_VALUE                      2448
